"""messages

Revision ID: 69da1d2ef488
Revises: 3225ddd744b6
Create Date: 2023-10-31 14:22:31.918156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69da1d2ef488'
down_revision = '3225ddd744b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=80), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
