"""forgot password token

Revision ID: 99c7eb04869a
Revises: f2d3395039b7
Create Date: 2023-10-03 19:08:10.600741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c7eb04869a'
down_revision = 'f2d3395039b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forgot_password_token', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('forgot_password_token')

    # ### end Alembic commands ###
